version: "3.3"

services:

  activemq-remote:
    image: webcenter/activemq:latest
    ports:
      # mqtt
      - "1882:1881"
      # amqp
      - "5673:5672"
      # ui
      - "8162:8161"
      # stomp
      - "62613:61613"
      # ws
      - "62614:61614"
      # jms
      - "62616:61616"
    networks: 
      activemq-network:
        ipv4_address: 172.28.0.3
    volumes: 
      - ./conf:/opt/activemq/conf
      - ./data:/data/activemq
      - ./log:/var/log/activemq
    environment:
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: "true"
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: password
      ACTIVEMQ_WRITE_LOGIN: write
      ACTIVEMQ_WRITE_PASSWORD: password
      ACTIVEMQ_READ_LOGIN: read
      ACTIVEMQ_READ_PASSWORD: password
      ACTIVEMQ_JMX_LOGIN: jmx
      ACTIVEMQ_JMX_PASSWORD: password
      ACTIVEMQ_STATIC_QUEUES: openmrs.sync.queue
      ACTIVEMQ_ENABLED_SCHEDULER: "true"
      ACTIVEMQ_MIN_MEMORY: 512
      ACTIVEMQ_MAX_MEMORY: 2048

networks:
  activemq-network:
    external:
      name: activemq-network
